/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./frontend/index.html",
    "./frontend/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1b1b1b",
        "surface-bright": "#f9f9fb",
        "surface-container": "#eeeef0",
        "tertiary-container": "#001e2b",
        "on-tertiary-fixed-variant": "#004d67",
        "secondary-container": "#0070eb",
        "primary-fixed-dim": "#c6c6c6",
        "glass-fill": "rgba(255, 255, 255, 0.7)",
        "outline": "#7e7576",
        "tertiary-fixed-dim": "#74d1ff",
        "on-secondary-fixed": "#001a41",
        "on-primary-fixed-variant": "#474747",
        "inverse-on-surface": "#f0f0f2",
        "primary": "#000000",
        "on-tertiary-fixed": "#001e2b",
        "outline-variant": "#cfc4c5",
        "on-secondary": "#ffffff",
        "system-gray": "#8E8E93",
        "surface-variant": "#e2e2e4",
        "background": "#f9f9fb",
        "on-tertiary-container": "#008ebb",
        "surface-container-low": "#f3f3f5",
        "tertiary-fixed": "#c1e8ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e4",
        "on-secondary-fixed-variant": "#004493",
        "on-surface": "#1a1c1d",
        "on-secondary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3132",
        "secondary-fixed": "#d8e2ff",
        "inverse-primary": "#c6c6c6",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadc",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-tint": "#5e5e5e",
        "secondary": "#0058bc",
        "on-background": "#1a1c1d",
        "surface": "#f9f9fb",
        "on-surface-variant": "#4c4546",
        "surface-container-high": "#e8e8ea",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-container": "#848484",
        "primary-fixed": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#adc6ff",
        "on-error-container": "#93000a",
        "surface-white": "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-padding": "120px",
        "container-max": "1200px",
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Text\"",
          "\"SF Pro Display\"",
          "\"SF Pro Icons\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "body-lg": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Text\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "body-md": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Text\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "headline-xl": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Display\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "headline-md": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Display\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "display-lg-mobile": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Display\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "display-lg": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Display\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
        "label-md": [
          "-apple-system",
          "BlinkMacSystemFont",
          "\"SF Pro Text\"",
          "\"Helvetica Neue\"",
          "Helvetica",
          "Arial",
          "sans-serif"
        ],
      },
      fontSize: {
        "body-lg": ["17px", { lineHeight: "1.5", letterSpacing: "-0.015em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.45", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-xl": ["24px", { lineHeight: "1.3", letterSpacing: "-0.021em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.35", letterSpacing: "-0.018em", fontWeight: "600" }],
        "display-lg-mobile": ["28px", { lineHeight: "1.25", letterSpacing: "-0.024em", fontWeight: "700" }],
        "display-lg": ["44px", { lineHeight: "1.15", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "1.35", letterSpacing: "-0.008em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      boxShadow: {
        card: "0 10px 40px rgba(0,0,0,0.04)",
        "card-hover": "0 20px 60px rgba(0,0,0,0.08)",
        cta: "0 8px 16px rgba(0,0,0,0.1)",
      },
    },
  },
  plugins: [],
};
